export const ATLAS_PRESETS = Object.freeze({
  uniform_grid: {
    id: 'uniform_grid',
    name: 'Uniform Grid Sheet',
    description: 'Clean sheets with fixed cell width/height.',
    backgroundMode: 'transparent_alpha',
    tolerance: 8,
    edgeFloodFill: true,
    minObjectArea: 20,
    tinyNoiseCutoff: 8,
    characterMergeDistance: 0,
    projectileMergeDistance: 0,
    cropPadding: 0,
    rowClusterTolerance: 0,
    largeGapSplitThreshold: 0,
    ignoreThinAnnotations: false,
    detectPortraits: false,
    detectProjectileRows: false,
    panelDetection: false,
    dividerDetection: false,
    tinySpriteMode: false,
    sectionDetection: false,
    multiEntity: false,
    paletteStripIgnore: false,
    textIgnore: false,
    requireManualReview: false
  },
  transparent_atlas: {
    id: 'transparent_atlas',
    name: 'Transparent Atlas Sheet',
    description: 'Sheets using alpha transparency without a regular grid.',
    backgroundMode: 'transparent_alpha',
    tolerance: 8,
    edgeFloodFill: false,
    minObjectArea: 20,
    tinyNoiseCutoff: 8,
    characterMergeDistance: 12,
    projectileMergeDistance: 6,
    cropPadding: 4,
    rowClusterTolerance: 24,
    largeGapSplitThreshold: 48,
    ignoreThinAnnotations: true,
    detectPortraits: true,
    detectProjectileRows: true,
    panelDetection: false,
    dividerDetection: false,
    tinySpriteMode: false,
    sectionDetection: false,
    multiEntity: false,
    paletteStripIgnore: false,
    textIgnore: true,
    requireManualReview: false
  },
  freeform_fighting: {
    id: 'freeform_fighting',
    name: 'Irregular Freeform Fighting Atlas',
    description: 'Green/mint chroma sheets with scattered frames.',
    backgroundMode: 'solid_chroma_edge_color',
    tolerance: 16,
    edgeFloodFill: true,
    minObjectArea: 20,
    tinyNoiseCutoff: 8,
    characterMergeDistance: 12,
    projectileMergeDistance: 6,
    cropPadding: 4,
    rowClusterTolerance: 24,
    largeGapSplitThreshold: 48,
    ignoreThinAnnotations: true,
    detectPortraits: true,
    detectProjectileRows: true,
    panelDetection: false,
    dividerDetection: false,
    tinySpriteMode: false,
    sectionDetection: false,
    multiEntity: false,
    paletteStripIgnore: true,
    textIgnore: true,
    requireManualReview: false
  },
  panel_fighting: {
    id: 'panel_fighting',
    name: 'Panel-Based Fighting Atlas',
    description: 'Dark sheets with visible divider lines and boxed panels.',
    backgroundMode: 'dark_presentation_background',
    tolerance: 24,
    edgeFloodFill: true,
    minObjectArea: 20,
    tinyNoiseCutoff: 8,
    characterMergeDistance: 12,
    projectileMergeDistance: 6,
    cropPadding: 2,
    rowClusterTolerance: 24,
    largeGapSplitThreshold: 48,
    ignoreThinAnnotations: true,
    detectPortraits: true,
    detectProjectileRows: true,
    panelDetection: true,
    dividerDetection: true,
    tinySpriteMode: false,
    sectionDetection: false,
    multiEntity: false,
    paletteStripIgnore: true,
    textIgnore: true,
    requireManualReview: false
  },
  jrpg_tiny: {
    id: 'jrpg_tiny',
    name: 'JRPG Tiny Multi-Animation Sheet',
    description: 'Small teal-background SNES-style sheets.',
    backgroundMode: 'solid_chroma_edge_color',
    tolerance: 12,
    edgeFloodFill: true,
    minObjectArea: 8,
    tinyNoiseCutoff: 4,
    characterMergeDistance: 6,
    projectileMergeDistance: 4,
    cropPadding: 2,
    rowClusterTolerance: 12,
    largeGapSplitThreshold: 24,
    ignoreThinAnnotations: true,
    detectPortraits: true,
    detectProjectileRows: false,
    panelDetection: false,
    dividerDetection: false,
    tinySpriteMode: true,
    sectionDetection: false,
    multiEntity: false,
    paletteStripIgnore: true,
    textIgnore: true,
    requireManualReview: false
  },
  compilation: {
    id: 'compilation',
    name: 'Compilation / Reference Sheet',
    description: 'Large monster/NPC catalog sheets with many entities.',
    backgroundMode: 'solid_chroma_dominant_color',
    tolerance: 16,
    edgeFloodFill: true,
    minObjectArea: 20,
    tinyNoiseCutoff: 8,
    characterMergeDistance: 12,
    projectileMergeDistance: 6,
    cropPadding: 4,
    rowClusterTolerance: 32,
    largeGapSplitThreshold: 64,
    ignoreThinAnnotations: true,
    detectPortraits: true,
    detectProjectileRows: true,
    panelDetection: false,
    dividerDetection: false,
    tinySpriteMode: false,
    sectionDetection: true,
    multiEntity: true,
    paletteStripIgnore: true,
    textIgnore: true,
    requireManualReview: true
  },
  fx_projectile: {
    id: 'fx_projectile',
    name: 'FX / Projectile Sheet',
    description: 'Energy effects, projectiles, smoke, flames, status flashes.',
    backgroundMode: 'transparent_alpha',
    tolerance: 8,
    edgeFloodFill: false,
    minObjectArea: 12,
    tinyNoiseCutoff: 6,
    characterMergeDistance: 8,
    projectileMergeDistance: 4,
    cropPadding: 2,
    rowClusterTolerance: 20,
    largeGapSplitThreshold: 40,
    ignoreThinAnnotations: true,
    detectPortraits: false,
    detectProjectileRows: false,
    panelDetection: false,
    dividerDetection: false,
    tinySpriteMode: false,
    sectionDetection: false,
    multiEntity: false,
    paletteStripIgnore: false,
    textIgnore: true,
    requireManualReview: false
  },
  manual_hybrid: {
    id: 'manual_hybrid',
    name: 'Manual / Hybrid Import',
    description: 'User draws crop regions manually with optional auto-detect per region.',
    backgroundMode: 'unknown',
    tolerance: 16,
    edgeFloodFill: true,
    minObjectArea: 10,
    tinyNoiseCutoff: 4,
    characterMergeDistance: 8,
    projectileMergeDistance: 4,
    cropPadding: 2,
    rowClusterTolerance: 16,
    largeGapSplitThreshold: 32,
    ignoreThinAnnotations: false,
    detectPortraits: false,
    detectProjectileRows: false,
    panelDetection: false,
    dividerDetection: false,
    tinySpriteMode: false,
    sectionDetection: false,
    multiEntity: false,
    paletteStripIgnore: false,
    textIgnore: false,
    requireManualReview: true
  }
});

export function getPreset(id) {
  return ATLAS_PRESETS[id] || ATLAS_PRESETS.manual_hybrid;
}

export function presetIds() {
  return Object.keys(ATLAS_PRESETS);
}
